# This file is for PRODUCTION SERVER
#
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "440a268a41ffc4afe9caa1aee5a3bfb7"
name = "Quickorderapp-prod"
handle = "quickorderapp-prod"
application_url = "https://quickorderappprod.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emertest2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://quickorderappprod.fly.dev/auth/callback",
  "https://quickorderappprod.fly.dev/auth/shopify/callback",
  "https://quickorderappprod.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
