# this file is in example for the toml file if incase it doesnot work
#
#
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration


client_id = "9d23bb7e571acde512ce6ec4ce48fa68"
name = "quickorder"
handle = "quickorder-5"
application_url = "https://quickorderappprod.fly.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emertest2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://quickorderappprod.fly.dev/auth/callback",
  "https://quickorderappprod.fly.dev/auth/shopify/callback",
  "https://quickorderappprod.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
