# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c502cc764e15465c6244e07b8401e8ca"
name = "QuickOrderApp-prod1"
handle = "quickorderapp-prod1"
application_url = "https://vids-equity-collapse-gr.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emertest2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://vids-equity-collapse-gr.trycloudflare.com/auth/callback",
  "https://vids-equity-collapse-gr.trycloudflare.com/auth/shopify/callback",
  "https://vids-equity-collapse-gr.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://vids-equity-collapse-gr.trycloudflare.com/userdata"
subpath = "proxy-1"
prefix = "apps"

[pos]
embedded = false
